// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hero struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Hp                   int32    `protobuf:"varint,2,opt,name=Hp,proto3" json:"Hp,omitempty"`
	Mp                   int32    `protobuf:"varint,3,opt,name=Mp,proto3" json:"Mp,omitempty"`
	Attack               int32    `protobuf:"varint,4,opt,name=Attack,proto3" json:"Attack,omitempty"`
	Defense              int32    `protobuf:"varint,5,opt,name=Defense,proto3" json:"Defense,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Hero) GetMp() int32 {
	if m != nil {
		return m.Mp
	}
	return 0
}

func (m *Hero) GetAttack() int32 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *Hero) GetDefense() int32 {
	if m != nil {
		return m.Defense
	}
	return 0
}

type Scene struct {
	Heros                []*Hero  `protobuf:"bytes,1,rep,name=Heros,proto3" json:"Heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scene) Reset()         { *m = Scene{} }
func (m *Scene) String() string { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()    {}
func (*Scene) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Scene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scene.Unmarshal(m, b)
}
func (m *Scene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scene.Marshal(b, m, deterministic)
}
func (m *Scene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scene.Merge(m, src)
}
func (m *Scene) XXX_Size() int {
	return xxx_messageInfo_Scene.Size(m)
}
func (m *Scene) XXX_DiscardUnknown() {
	xxx_messageInfo_Scene.DiscardUnknown(m)
}

var xxx_messageInfo_Scene proto.InternalMessageInfo

func (m *Scene) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

type Action struct {
	SrcHeroId            int32    `protobuf:"varint,1,opt,name=SrcHeroId,proto3" json:"SrcHeroId,omitempty"`
	TargetHeroId         int32    `protobuf:"varint,2,opt,name=TargetHeroId,proto3" json:"TargetHeroId,omitempty"`
	SkillType            int32    `protobuf:"varint,3,opt,name=SkillType,proto3" json:"SkillType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetSrcHeroId() int32 {
	if m != nil {
		return m.SrcHeroId
	}
	return 0
}

func (m *Action) GetTargetHeroId() int32 {
	if m != nil {
		return m.TargetHeroId
	}
	return 0
}

func (m *Action) GetSkillType() int32 {
	if m != nil {
		return m.SkillType
	}
	return 0
}

type JoinRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

type JoinResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Hero)(nil), "game.Hero")
	proto.RegisterType((*Scene)(nil), "game.Scene")
	proto.RegisterType((*Action)(nil), "game.Action")
	proto.RegisterType((*JoinRequest)(nil), "game.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "game.JoinResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0xd4, 0x0e, 0xe2, 0x5a, 0x18, 0x6e, 0x40, 0x1e, 0x18, 0x22, 0x4f, 0x65, 0xe9,
	0x00, 0x4f, 0x50, 0xc1, 0x90, 0x22, 0x75, 0x49, 0xfb, 0x02, 0xc1, 0x39, 0xda, 0xa8, 0xc5, 0x36,
	0xb6, 0x19, 0x78, 0x7b, 0xe4, 0x3f, 0x50, 0xb1, 0xdd, 0xef, 0x77, 0x96, 0xbf, 0x4f, 0x07, 0x70,
	0x18, 0x3e, 0x68, 0x65, 0x9d, 0x09, 0x06, 0x59, 0x9c, 0xe5, 0x11, 0x58, 0x47, 0xce, 0xe0, 0x2d,
	0xd4, 0x9b, 0x51, 0x54, 0x6d, 0xb5, 0xe4, 0x7d, 0xbd, 0x19, 0x23, 0x77, 0x56, 0xd4, 0x99, 0x3b,
	0x1b, 0x79, 0x6b, 0xc5, 0x2c, 0xf3, 0xd6, 0xe2, 0x1d, 0x34, 0xeb, 0x10, 0x06, 0x75, 0x12, 0x2c,
	0xb9, 0x42, 0x28, 0xe0, 0xea, 0x85, 0xde, 0x49, 0x7b, 0x12, 0x3c, 0x2d, 0x7e, 0x51, 0x3e, 0x00,
	0xdf, 0x29, 0xd2, 0x84, 0x2d, 0xf0, 0x18, 0xe9, 0x45, 0xd5, 0xce, 0x96, 0xf3, 0x47, 0x58, 0xa5,
	0x52, 0x51, 0xf5, 0x79, 0x21, 0x8f, 0xd0, 0xac, 0x55, 0x98, 0x8c, 0xc6, 0x7b, 0xb8, 0xde, 0x39,
	0x15, 0xed, 0x5f, 0xbb, 0x8b, 0x40, 0x09, 0x8b, 0xfd, 0xe0, 0x0e, 0x14, 0xca, 0x83, 0x5c, 0xf7,
	0x9f, 0x4b, 0x3f, 0x9c, 0xa6, 0xf3, 0x79, 0xff, 0x6d, 0xa9, 0xf4, 0xbf, 0x08, 0x79, 0x03, 0xf3,
	0x57, 0x33, 0xe9, 0x9e, 0x3e, 0xbf, 0xc8, 0x07, 0x29, 0x61, 0x91, 0xd1, 0x5b, 0xa3, 0x3d, 0x21,
	0x02, 0x7b, 0x36, 0x23, 0x95, 0xe4, 0x34, 0xbf, 0x35, 0xe9, 0x7c, 0x4f, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x4b, 0xd8, 0x23, 0x8f, 0x4c, 0x01, 0x00, 0x00,
}
