// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package pbgame

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hero struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Hp                   int32    `protobuf:"varint,2,opt,name=Hp,proto3" json:"Hp,omitempty"`
	Mp                   int32    `protobuf:"varint,3,opt,name=Mp,proto3" json:"Mp,omitempty"`
	Attack               int32    `protobuf:"varint,4,opt,name=Attack,proto3" json:"Attack,omitempty"`
	Defense              int32    `protobuf:"varint,5,opt,name=Defense,proto3" json:"Defense,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_6099a8a13d17510a, []int{0}
}
func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (dst *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(dst, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Hero) GetMp() int32 {
	if m != nil {
		return m.Mp
	}
	return 0
}

func (m *Hero) GetAttack() int32 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *Hero) GetDefense() int32 {
	if m != nil {
		return m.Defense
	}
	return 0
}

type Scene struct {
	Heros                []*Hero  `protobuf:"bytes,1,rep,name=Heros,proto3" json:"Heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scene) Reset()         { *m = Scene{} }
func (m *Scene) String() string { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()    {}
func (*Scene) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_6099a8a13d17510a, []int{1}
}
func (m *Scene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scene.Unmarshal(m, b)
}
func (m *Scene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scene.Marshal(b, m, deterministic)
}
func (dst *Scene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scene.Merge(dst, src)
}
func (m *Scene) XXX_Size() int {
	return xxx_messageInfo_Scene.Size(m)
}
func (m *Scene) XXX_DiscardUnknown() {
	xxx_messageInfo_Scene.DiscardUnknown(m)
}

var xxx_messageInfo_Scene proto.InternalMessageInfo

func (m *Scene) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

type Action struct {
	SrcHeroId            int32    `protobuf:"varint,1,opt,name=SrcHeroId,proto3" json:"SrcHeroId,omitempty"`
	TargetHeroId         int32    `protobuf:"varint,2,opt,name=TargetHeroId,proto3" json:"TargetHeroId,omitempty"`
	SkillType            int32    `protobuf:"varint,3,opt,name=SkillType,proto3" json:"SkillType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_6099a8a13d17510a, []int{2}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetSrcHeroId() int32 {
	if m != nil {
		return m.SrcHeroId
	}
	return 0
}

func (m *Action) GetTargetHeroId() int32 {
	if m != nil {
		return m.TargetHeroId
	}
	return 0
}

func (m *Action) GetSkillType() int32 {
	if m != nil {
		return m.SkillType
	}
	return 0
}

type JoinRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_6099a8a13d17510a, []int{3}
}
func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (dst *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(dst, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

type JoinResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_game_6099a8a13d17510a, []int{4}
}
func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (dst *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(dst, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Hero)(nil), "pbgame.Hero")
	proto.RegisterType((*Scene)(nil), "pbgame.Scene")
	proto.RegisterType((*Action)(nil), "pbgame.Action")
	proto.RegisterType((*JoinRequest)(nil), "pbgame.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "pbgame.JoinResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_game_6099a8a13d17510a) }

var fileDescriptor_game_6099a8a13d17510a = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x34, 0x09, 0xe2, 0x1a, 0x18, 0x6e, 0x40, 0x1e, 0x18, 0xaa, 0x9b, 0x2a, 0x21,
	0x65, 0x80, 0x27, 0xa8, 0x60, 0x48, 0x91, 0xba, 0xa4, 0x7d, 0x81, 0x34, 0x39, 0xda, 0xa8, 0xc5,
	0x3e, 0x62, 0x33, 0xf0, 0xf6, 0xc8, 0x76, 0xa0, 0xea, 0xe6, 0xef, 0x3b, 0xcb, 0xff, 0xef, 0x03,
	0x38, 0xb4, 0x9f, 0x5c, 0xc9, 0x68, 0x9c, 0xc1, 0x42, 0xf6, 0x9e, 0xe8, 0x08, 0x59, 0xcd, 0xa3,
	0xc1, 0x7b, 0x48, 0xd7, 0xbd, 0x4a, 0x16, 0xc9, 0x32, 0x6f, 0xd2, 0x75, 0xef, 0xb9, 0x16, 0x95,
	0x46, 0xae, 0xc5, 0xf3, 0x46, 0xd4, 0x2c, 0xf2, 0x46, 0xf0, 0x01, 0x8a, 0x95, 0x73, 0x6d, 0x77,
	0x52, 0x59, 0x70, 0x13, 0xa1, 0x82, 0x9b, 0x37, 0xfe, 0x60, 0x6d, 0x59, 0xe5, 0x61, 0xf0, 0x87,
	0xf4, 0x04, 0xf9, 0xb6, 0x63, 0xcd, 0x48, 0x90, 0xfb, 0x48, 0xab, 0x92, 0xc5, 0x6c, 0x39, 0x7f,
	0x2e, 0xab, 0x58, 0xa5, 0xf2, 0xb2, 0x89, 0x23, 0x3a, 0x42, 0xb1, 0xea, 0xdc, 0x60, 0x34, 0x3e,
	0xc2, 0xed, 0x76, 0xec, 0xbc, 0xfd, 0xef, 0x77, 0x11, 0x48, 0x50, 0xee, 0xda, 0xf1, 0xc0, 0x6e,
	0xba, 0x10, 0x0b, 0x5f, 0xb9, 0xf0, 0xc2, 0x69, 0x38, 0x9f, 0x77, 0x3f, 0xc2, 0xd3, 0x0f, 0x2e,
	0x82, 0xee, 0x60, 0xfe, 0x6e, 0x06, 0xdd, 0xf0, 0xd7, 0x37, 0x5b, 0x47, 0x04, 0x65, 0x44, 0x2b,
	0x46, 0x5b, 0x46, 0x84, 0xec, 0xd5, 0xf4, 0x3c, 0x25, 0x87, 0xf3, 0xbe, 0x08, 0x2b, 0x7c, 0xf9,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x50, 0x15, 0x71, 0x50, 0x01, 0x00, 0x00,
}
